export const SET_WALLET_INSTALLED = 'SET_WALLET_INSTALLED'
export const SET_WALLET_CONNECTED = 'SET_WALLET_CONNECTED'
export const SET_ACCOUNT = 'SET_ACCOUNT'
export const SET_WAVES_RECEIVED = 'SET_WAVES_RECEIVED'
export const SET_MINING = 'SET_MINING'
export const SET_CLEANED_WAVES = 'SET_CLEANED_WAVES'


